"""empty message

Revision ID: c140982ec9d2
Revises: 23d454425300
Create Date: 2023-03-11 16:37:46.078844

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c140982ec9d2'
down_revision = '23d454425300'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.add_column(sa.Column('multiple_allowed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.drop_column('multiple_allowed')

    # ### end Alembic commands ###
