"""init

Revision ID: 1731100369
Revises:
Create Date: 2024-11-08 21:12:49.823551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1731100369"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ("default",)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "survey",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("topic", sa.String(length=50), nullable=False),
        sa.Column("question", sa.String(length=150), nullable=False),
        sa.Column("options", sa.String(length=500), nullable=False),
        sa.Column("multiple_allowed", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "answer",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("survey", sa.Integer(), nullable=False),
        sa.Column("selected_option", sa.String(length=500), nullable=False),
        sa.ForeignKeyConstraint(["survey"], ["survey.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("answer")
    op.drop_table("survey")
    # ### end Alembic commands ###
